### ISSUE TITLE
Enhancement: jar

### ISSUE THREAD

**Issue by yurilaguta** [coocood/VContentProvider#4]
It should be possible to use as a jar, since you don't use any xml resources if I'm not mistaken.

P.S. Really love the idea

**Comment by coocood** [comment]
Yes, you can make it yourself. but as the source code is small, I think it doesn't bring much benefits to use as a jar.

**Comment by yurilaguta** [comment]
It much more convenient just to get jar from library and start using it immediately instead on loading project, compiling and then play with it.

Another benefit of jar is that you don't have to have another library project.

**Comment by coocood** [comment]
added
